### 1. Fazer Login e Capturar Token
# @name login
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "joao@email.com",
  "password": "senhaSuperSecreta123"
}

### Guardando o token retornado
@token = {{login.response.body.token}}


### 2. Testar Rota Protegida SEM Token (Deve retornar 401)
GET http://localhost:3000/profile


### 3. Testar Rota Protegida COM Token (Deve retornar 200 OK)
GET http://localhost:3000/profile
Authorization: Bearer {{token}}


### 4. Testar Rota ADMIN com perfil ATTENDANT (Deve retornar 403 Acesso Negado)
GET http://localhost:3000/admin
Authorization: Bearer {{token}}